### ISSUE TITLE
Make Navbar Sticky 

### ISSUE THREAD

**Issue by thetarandhiman** [MicrosoftStudentChapter/Hacktoberfest2021#25]

**Comment by Himanshu664** [comment]
@ritikrajdev I want to work please assign.

**Comment by NaveenKharwar** [comment]
Hi @thetarandhiman, please add more information on your issue.

**Comment by thetarandhiman** [comment]
Closed the issue with merging of PRs #40 & #39 !

**Comment by thetarandhiman** [comment]
> 
> 
> Hi @thetarandhiman, please add more information on your issue.

For now, the issue has been closed! Thanks! Happy hacking!
